# Generated by Django 3.0.7 on 2020-06-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='活动名称')),
                ('datetime_start', models.DateTimeField(verbose_name='活动开始时间')),
                ('datetime_end', models.DateTimeField(verbose_name='活动结束时间')),
                ('main_image', models.ImageField(upload_to='')),
                ('number_people', models.IntegerField()),
                ('address', models.CharField(max_length=128, verbose_name='活动地址')),
                ('view_number', models.IntegerField()),
                ('like_number', models.IntegerField()),
                ('partner', models.CharField(max_length=128)),
                ('important_guests', models.CharField(max_length=32)),
                ('tag', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='文章标题')),
                ('post_datetime', models.DateTimeField(auto_now_add=True, verbose_name='文章发布日期')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('thumb_up', models.PositiveIntegerField(verbose_name='点赞数')),
                ('view_num', models.PositiveIntegerField(verbose_name='浏览数')),
                ('reply_num', models.PositiveIntegerField(verbose_name='回复数')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='学院帖子详情')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='活动详情')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Activity')),
            ],
        ),
    ]
