# Generated by Django 3.0.7 on 2020-06-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params2Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='商品名称')),
                ('product_img', models.ImageField(upload_to='products')),
                ('product_type', models.SmallIntegerField(choices=[(0, '纪念品'), (1, '书籍'), (2, '文化衫')])),
                ('post_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('status', models.SmallIntegerField(choices=[(0, '预定中'), (1, '售卖中'), (2, '已售空')])),
            ],
        ),
        migrations.CreateModel(
            name='ProductsParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='产品的参数')),
                ('product', models.ManyToManyField(through='app01.Params2Products', to='app01.Products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2048, verbose_name='商品描述')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Products')),
            ],
        ),
        migrations.AddField(
            model_name='params2products',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ProductsParams'),
        ),
        migrations.AddField(
            model_name='params2products',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Products'),
        ),
    ]
