# Generated by Django 3.0.7 on 2020-06-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app01', '0002_auto_20200608_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('uid', models.CharField(help_text='微信用户绑定和CC视频统计', max_length=64, unique=True)),
                ('openid', models.CharField(blank=True, max_length=128, null=True)),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='可提现和使用余额')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='合作方名称')),
                ('breif', models.TextField(max_length=1024, verbose_name='合作方简介')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='like_number',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.SmallIntegerField(choices=[(0, '免费'), (1, '收费')], default=0, verbose_name='活动的费用类型'),
        ),
        migrations.AddField(
            model_name='activity',
            name='collect_number',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='institute',
            name='main_image',
            field=models.ImageField(null=True, upload_to='institute'),
        ),
        migrations.AddField(
            model_name='institute',
            name='tag',
            field=models.CharField(max_length=32, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='main_image',
            field=models.ImageField(null=True, upload_to='activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='number_people',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='partner',
        ),
        migrations.AlterField(
            model_name='activity',
            name='tag',
            field=models.CharField(max_length=32, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='view_number',
            field=models.PositiveIntegerField(verbose_name='浏览数'),
        ),
        migrations.CreateModel(
            name='UserAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField(max_length=1024)),
                ('disagree_number', models.IntegerField(default=0, verbose_name='踩')),
                ('agree_number', models.IntegerField(default=0, verbose_name='赞同数')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Account', verbose_name='会员名')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='类型')),
                ('p_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Comment', verbose_name='父级评论')),
            ],
            options={
                'verbose_name_plural': '19. 通用评论表',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='partner',
            field=models.ManyToManyField(to='app01.Partner'),
        ),
    ]
