# Generated by Django 3.0.7 on 2020-06-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200608_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_status',
            field=models.SmallIntegerField(choices=[(0, '正在报名'), (1, '正在进行'), (2, '已过期')], default=0),
        ),
    ]
