# Generated by Django 3.0.7 on 2020-06-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_activity_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='可提现和使用余额'),
        ),
    ]
