# Generated by Django 3.0.7 on 2020-06-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20200611_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='tag',
        ),
        migrations.AddField(
            model_name='activity',
            name='tag',
            field=models.ManyToManyField(null=True, to='app01.Tag', verbose_name='标签'),
        ),
        migrations.RemoveField(
            model_name='institute',
            name='tag',
        ),
        migrations.AddField(
            model_name='institute',
            name='tag',
            field=models.ManyToManyField(null=True, to='app01.Tag', verbose_name='标签'),
        ),
    ]
