# Generated by Django 3.0.7 on 2020-06-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20200611_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='important_guests',
        ),
        migrations.AddField(
            model_name='activity',
            name='important_guests',
            field=models.ManyToManyField(to='app01.Account'),
        ),
    ]
