# Generated by Django 3.0.7 on 2020-06-11 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20200611_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydetail',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.Activity'),
        ),
        migrations.AlterField(
            model_name='institutedetail',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.Institute'),
        ),
    ]
