# Generated by Django 3.0.7 on 2020-06-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20200611_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('brief', models.TextField(verbose_name='专题的详情')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.SmallIntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=2)),
                ('institute', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.Institute')),
            ],
        ),
        migrations.AddField(
            model_name='institute',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.subjectList'),
        ),
    ]
