# Generated by Django 3.0.7 on 2020-06-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20200612_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='subject',
        ),
        migrations.AddField(
            model_name='subjectlist',
            name='article',
            field=models.ManyToManyField(to='app01.Institute'),
        ),
    ]
