# Generated by Django 3.0.7 on 2020-06-14 14:00

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_subjectlist_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='weights',
            field=models.SmallIntegerField(choices=[(0, '普通会员'), (1, '活跃会员'), (2, '品质会员'), (3, '优质会员')], default=0),
        ),
        migrations.AlterField(
            model_name='subjectlist',
            name='main_image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='subject'),
        ),
    ]
