# Generated by Django 3.0.7 on 2020-06-14 15:35

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_auto_20200614_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activity',
            field=models.ManyToManyField(blank=True, to='app01.Activity', verbose_name='参加的活动'),
        ),
        migrations.AddField(
            model_name='account',
            name='article',
            field=models.ManyToManyField(blank=True, to='app01.Institute', verbose_name='发布的文章'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='important_guests',
            field=models.ManyToManyField(related_name='important_guests', to='app01.Account'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app01.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app01.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='products'),
        ),
    ]
