# Generated by Django 3.0.7 on 2020-06-15 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_auto_20200615_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='parmas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.ProductsParams'),
        ),
    ]
