# Generated by Django 3.0.7 on 2020-06-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_products_parmas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='parmas',
        ),
    ]
