# Generated by Django 3.0.7 on 2020-06-15 07:06

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_auto_20200615_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='main_image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='institute'),
        ),
    ]
