# Generated by Django 3.0.7 on 2020-06-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0029_auto_20200615_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='orderpeople_num',
            field=models.IntegerField(default=0, verbose_name='当前报名人数'),
        ),
    ]
