# Generated by Django 3.0.7 on 2020-06-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_activity_orderpeople_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='reply_num',
            field=models.PositiveIntegerField(default=0, verbose_name='回复数'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='thumb_up',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='view_num',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览数'),
        ),
    ]
