# Generated by Django 3.0.7 on 2020-06-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0032_auto_20200616_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='author',
            field=models.ForeignKey(blank=True, max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_author', to='app01.Account', verbose_name='作者'),
        ),
    ]
